### PR TITLE
Memory and performance enhancements

### PR DESCRIPTION
**Pull request by dralley**
[noissue]

### CODE REVIEW

**Comment by dralley** [comment]
W/ this code I run into an error on the createrepo_c parsing side of things.  @goosemania have you seen this before?  The file contents look fine to me...

```
Mar 10 20:25:59 pulp2-nightly-pulp3-source-centos7.localhost.example.com rq[30133]: future: <Task finished coro=<ContentMigrationFirstStage.migrate_to_pulp3() done, defined at /home/vagrant/devel/pulp-2to3-migration/pulp_2to3_migration/app/plugin/content.py:176> exception=CreaterepoCError('Cannot open /tmp/tmplh02pgei/tmpkh6jsdhe: Cannot detect compression type',)>
Mar 10 20:25:59 pulp2-nightly-pulp3-source-centos7.localhost.example.com rq[30133]: Traceback (most recent call last):
Mar 10 20:25:59 pulp2-nightly-pulp3-source-centos7.localhost.example.com rq[30133]: File "/home/vagrant/devel/pulp-2to3-migration/pulp_2to3_migration/app/plugin/content.py", line 214, in migrate_to_pulp3
Mar 10 20:25:59 pulp2-nightly-pulp3-source-centos7.localhost.example.com rq[30133]: pulp3content = await pulp_2to3_detail_content.create_pulp3_content()
Mar 10 20:25:59 pulp2-nightly-pulp3-source-centos7.localhost.example.com rq[30133]: File "/home/vagrant/devel/pulp-2to3-migration/pulp_2to3_migration/app/plugin/rpm/pulp_2to3_models.py", line 118, in create_pulp3_content
Mar 10 20:25:59 pulp2-nightly-pulp3-source-centos7.localhost.example.com rq[30133]: return Package(**pkg_dict)
Mar 10 20:25:59 pulp2-nightly-pulp3-source-centos7.localhost.example.com rq[30133]: File "/home/vagrant/devel/pulp-2to3-migration/pulp_2to3_migration/app/plugin/rpm/xml_utils.py", line 221, in get_cr_obj
Mar 10 20:25:59 pulp2-nightly-pulp3-source-centos7.localhost.example.com rq[30133]: filenames['filelists'])
Mar 10 20:25:59 pulp2-nightly-pulp3-source-centos7.localhost.example.com rq[30133]: File "/home/vagrant/devel/pulp_rpm/pulp_rpm/app/tasks/synchronizing.py", line 286, in parse_repodata
Mar 10 20:25:59 pulp2-nightly-pulp3-source-centos7.localhost.example.com rq[30133]: cr.xml_parse_filelists(filelists_xml_path, newpkgcb=newpkgcb)
Mar 10 20:25:59 pulp2-nightly-pulp3-source-centos7.localhost.example.com rq[30133]: File "/usr/local/lib/pulp/lib64/python3.6/site-packages/createrepo_c/__init__.py", line 316, in xml_parse_filelists
Mar 10 20:25:59 pulp2-nightly-pulp3-source-centos7.localhost.example.com rq[30133]: return _createrepo_c.xml_parse_filelists(path, newpkgcb, pkgcb, warningcb)
Mar 10 20:25:59 pulp2-nightly-pulp3-source-centos7.localhost.example.com rq[30133]: createrepo_c.CreaterepoCError: Cannot open /tmp/tmplh02pgei/tmpkh6jsdhe: Cannot detect compression type
```

Also one thing I noticed is that the XML stored in MongoDB from Pulp 2 is not "complete", it has template tags for ```{{ pkgid }}``` stored in it.  Would that cause problems for createrepo_c?

**Comment by goosemania** [comment]
@dralley , it's strange if you see that file looks fine.

There should be no template tags in the result file which goes into createrepo_c. It's taken care of here https://github.com/pulp/pulp-2to3-migration/pull/113/files#diff-f901af708b74ef5a79a941cfe2ebe8e0L192-R196 and here https://github.com/pulp/pulp-2to3-migration/pull/113/files#diff-f901af708b74ef5a79a941cfe2ebe8e0R213-R218

**Comment by dralley** [comment]
Depends on this PR: https://github.com/rpm-software-management/createrepo_c/pull/212

**Comment by dralley** [comment]
There is not much in the way of performance improvement at the moment.  It perhaps saves about 10%.
One thing that confuses me is that the call graph is massively larger post-xml-snippet-commit than it was before:

Before:
nocache_perf

After:
xml_snippet_perf

It doesn't really make sense to me since the only change, really, would be the callbacks, and they don't do anything more than get/set keys on a dict.

**Comment by dralley** [comment]
Unless it is passing more units through the pipeline for some reason, in which case, it might cause this explosion of extra work.  I haven't gotten that far nor have I really looked into the issue you mentioned.

**Comment by dralley** [comment]
@goosemania So I did some more testing:

Before this XML-snippet-patch it only migrated 628 content units total -- 620 RPMs and 8 Published metadata.  So the repository version created is incorrect. 

After the patch it migrates all 10,097 RPMs and associates them to the repository version correctly.  So that explains why it's not much faster -- because it's doing more work that wasn't happening beforehand for some reason.  I'm not sure why.  Maybe something is going on with the temp files and they aren't being saved or they're disappearing before they get parsed?

**Comment by dralley** [comment]
In conjunction with https://github.com/pulp/pulp_rpm/pull/1648

The (initial) migration time went from ~165 seconds to ~118 seconds (~30% improvement).

Re-migration times saw a similar improvement but are still longer than the initial migration time.

**Comment by goosemania** [comment]
@dralley , please do not squash commits so we can cherry-pick non-rpm stuff to the 0.1 branch.

**Comment by dralley** [comment]
Understood, I was planning on leaving them as-is

**Pull request merged**
