### PR TITLE
Fix migration of non-utf8 BSON-encoded module defaults metadata

### PR DESCRIPTION
**Pull request by dralley**
[noissue]

### CODE REVIEW

**Comment by dralley** [comment]
@ggainey We can leave this unmerged until @goosemania gets back I think, no rush, but I'd like your approval here before we merge the actual hotfix to pulp_rpm and advertise it.

**Review by ggainey — APPROVED** [review]

**Comment by goosemania** [comment]
@dralley , It looks good to me.
I read it as it needs to be backported to 0.11.z. If so,  please file a backport issue.

**Comment by dralley** [comment]
@goosemania Updated & filed

**Comment by goosemania** [comment]
@dralley , could you rebase, plz. I think I merged all the fixes for CI.

**Pull request merged**
