### PR TITLE
Don't log any warnings if at least one LCE has been migrated

### PR DESCRIPTION
**Pull request by goosemania**
re #7193
https://pulp.plan.io/issues/7193

### CODE REVIEW

**Comment by dralley** [comment]
@goosemania This is still marked draft, is it done?

**Comment by goosemania** [comment]
I believe it's done, just the issue number is probably wrong, I'll check.

**Review by ipanova — APPROVED** [review]

**Comment by ipanova** [comment]
@goosemania  needs an entry in changelog

**Comment by goosemania** [comment]
I'll open a separate PR, this will need a painful rebase and the issue number is off.

**Pull request closed without merging**
