### PR TITLE
Workflows documentation correct create a migration plan command

### PR DESCRIPTION
**Pull request by jalapenopuzzle**

### CODE REVIEW

**Comment by mdellweg** [comment]
Can you please add a line with `[noissue]` in the commit message, to pass the linting stage?

**Comment by jalapenopuzzle** [comment]
Added [noissue] to commit comment as requested.

**Comment by jalapenopuzzle** [comment]
I added the [noissue] to the commit comment, and CI has now passed the 
linting stage.

However, it is now detecting other coding issues. I only changed docs, 
did not touch the code, so it seems these issues are pre-existing.

Ben.

**Comment by dralley** [comment]
Yup, we've seen that issue a few times today, definitely unrelated.

**Review by dralley — APPROVED** [review]

**Review by goosemania — APPROVED** [review]

**Pull request merged**
