### PR TITLE
Rpm migration stucks for days

### LINKED ISSUE #568: Migration stucks in calculating total of rpms to be migrated and migrating rpms for days
**Version**
satellite-6.9.9-1.el7sat.noarch
tfm-rubygem-katello-3.18.1.53-1.el7sat.noarch
tfm-rubygem-pulp_2to3_migration_client-0.10.0-1.el7sat.noarch


**Describe the bug**
Cloned from https://bugzilla.redhat.com/show_bug.cgi?id=2097204


The migration could spent long time or stuck in calculating the total repository rpms to be migrated if the total is extremely large (e.g. 2 millions++).


As we can see below, the migration stuck in "Migrating content to Pulp 3" for 3 days without any progress
~~~
2022-06-09 19:49:08 +1000: Migrating docker_tag content to Pulp 3 57057/62272
2022-06-09 19:49:18 +1000: Migrating docker_tag content to Pulp 3 60060/62272
2022-06-09 19:49:38 +1000: Initial Migration steps complete.
2022-06-09 19:49:48 +1000: Migrating content to Pulp 3 606012/3485647
...
2022-06-10 10:14:14 +1000: Migrating content to Pulp 3 606012/3485647
2022-06-10 10:14:24 +1000: Migrating content to Pulp 3 606012/3485647
...
...
2022-06-11 14:16:21 +1000: Migrating content to Pulp 3 606012/3485647
~~~


Checking the postgres activities. We found that the "count()" query has been active since 3 days.
~~~
# su - postgres -c "psql foreman -c \"select * from pg_stat_activity where datname = 'pulpcore' and state <> 'idle';\""
  datid  | datname  |  pid  | usesysid | usename | application_name | client_addr | client_hostname | client_port |         backend_start         |          xact_start           |          query_start          |         state_change          | wait_event_type | wait_event | state  | backend_xid | backend_xmin |                                                                                                        
                                                                                                                               query                                                                                                                                                                                                                                       |  backend_type   
---------+----------+-------+----------+---------+------------------+-------------+-----------------+-------------+-------------------------------+-------------------------------+-------------------------------+-------------------------------+-----------------+------------+--------+-------------+--------------+------------------------------------------------+-----------------
 123456 | pulpcore | XXXXXX |  XXXXXX | pulp    |                  | XX.XX.XX.XX   |                 |       XXXXXX | 2022-06-08 11:57:11.798522+10 | 2022-06-09 19:49:35.186242+10 | 2022-06-09 19:49:35.186242+10 | 2022-06-09 19:49:35.186243+10 |                 |            | active |             |     XXXXXX | SELECT COUNT(*) AS "__count" FROM "pulp_2to3_migration_pulp2rpm" INNER JOIN "pulp_2to3_migration_pulp2c
ontent" ON ("pulp_2to3_migration_pulp2rpm"."pulp2content_id" = "pulp_2to3_migration_pulp2content"."pulp_id") WHERE NOT (NOT ("pulp_2to3_migration_pulp2content"."pulp3_content_id" IS NULL) AND NOT ("pulp_2to3_migration_pulp2content"."pulp2_id" IN (SELECT DISTINCT U0."pulp2_unit_id" FROM "pulp_2to3_migration_pulp2lazycatalog" U0 WHERE U0."is_migrated" = false))) | client backend

 123456 | pulpcore | XXXXXX |  XXXXXX | pulp    |                  |             |                 |             | 2022-06-09 19:49:35.191817+10 | 2022-06-09 19:49:35.186242+10 | 2022-06-09 19:49:35.186242+10 | 2022-06-09 19:49:35.196112+10 |                 |            | active |             |     XXXXXX | SELECT COUNT(*) AS "__count" FROM "pulp_2to3_migration_pulp2rpm" INNER JOIN "pulp_2to3_migration_pulp2c
ontent" ON ("pulp_2to3_migration_pulp2rpm"."pulp2content_id" = "pulp_2to3_migration_pulp2content"."pulp_id") WHERE NOT (NOT ("pulp_2to3_migration_pulp2content"."pulp3_content_id" IS NULL) AND NOT ("pulp_2to3_migration_pulp2content"."pulp2_id" IN (SELECT DISTINCT U0."pulp2_unit_id" FROM "pulp_2to3_migration_pulp2lazycatalog" U0 WHERE U0."is_migrated" = false))) | parallel worker

 123456 | pulpcore | XXXXXX |  XXXXXX | pulp    |                  |             |                 |             | 2022-06-09 19:49:35.192686+10 | 2022-06-09 19:49:35.186242+10 | 2022-06-09 19:49:35.186242+10 | 2022-06-09 19:49:35.196497+10 |                 |            | active |             |     XXXXXX | SELECT COUNT(*) AS "__count" FROM "pulp_2to3_migration_pulp2rpm" INNER JOIN "pulp_2to3_migration_pulp2c
ontent" ON ("pulp_2to3_migration_pulp2rpm"."pulp2content_id" = "pulp_2to3_migration_pulp2content"."pulp_id") WHERE NOT (NOT ("pulp_2to3_migration_pulp2content"."pulp3_content_id" IS NULL) AND NOT ("pulp_2to3_migration_pulp2content"."pulp2_id" IN (SELECT DISTINCT U0."pulp2_unit_id" FROM "pulp_2to3_migration_pulp2lazycatalog" U0 WHERE U0."is_migrated" = false))) | parallel worker
(3 rows)
~~~

We can see 1 RQ worker is busy
~~~
#ps -aux | grep '/usr/bin/rq
pulp     XXXXX 64.1  0.3 1468496 836400 ?      Sl   Jun08 1854:22 /usr/bin/python3 /usr/bin/rq worker -w pulpcore.tasking.worker.PulpWorker -c pulpcore.rqconfig --disable-job-desc-logging
~~~

Finally the count() query is completed after running  for 4.98 days.
~~~
2022-06-13 00:53:05 UTC LOG:  duration: 430300515.900 ms  statement: SELECT COUNT(*) AS "__count" FROM "pulp_2to3_migration_pulp2rpm" INNER JOIN "pulp_2to3_migration_pulp2content" ON ("pulp_2to3_migration_pulp2rpm"."pulp2content_id" = "pulp_2to3_migration_pulp2content"."pulp_id") WHERE NOT (NOT ("pulp_2to3_migration_pulp2content"."pulp3_content_id" IS NULL) AND NOT ("pulp_2to3_migration_pulp2content"."pulp2_id" IN (SELECT DISTINCT U0."pulp2_unit_id" FROM "pulp_2to3_migration_pulp2lazycatalog" U0 WHERE U0."is_migrated" = false)))
~~~


**Expected behavior**
Better performance

**Additional context**
I think the poor query could be caused by the large contents + the sub query (large Pulp2LazyCatalog).
~~~
# /usr/lib/python3.6/site-packages/pulp_2to3_migration/app/plugin/content.py

        if is_lazy_type:
            # go through all of the content that haven't been migrated OR have been migrated
            # but have new lazy catalog entries.
            units_with_new_lces = Pulp2LazyCatalog.objects.filter(
                is_migrated=False).values('pulp2_unit_id').distinct()
            already_migrated = ~Q(pulp2content__pulp3_content=None)
            no_new_lces = ~Q(pulp2content__pulp2_id__in=units_with_new_lces)
            pulp_2to3_detail_qs = content_model.objects.exclude(already_migrated & no_new_lces) <=============== this query
        else:
            # go through all of the content that haven't been migrated
            pulp_2to3_detail_qs = content_model.objects.filter(pulp2content__pulp3_content=None)

        # order by pulp2_repo if it's set
        if content_model.set_pulp2_repo:
            pulp_2to3_detail_qs = pulp_2to3_detail_qs.order_by('repo_id')

        with ProgressReport(
            message='Migrating {} content to Pulp 3'.format(content_type),
            code='migrating.{}.content'.format(self.migrator.pulp2_plugin),
            total=pulp_2to3_detail_qs.count()   <=================================== stuck here for days
       ) as pb:
            select_extra = [
                'pulp2content',
                'pulp2content__pulp3_content',
            ]

            if content_model.set_pulp2_repo:
                select_extra.append('pulp2content__pulp2_repo')

            pulp_2to3_detail_qs = pulp_2to3_detail_qs.select_related(*select_extra)
            for pulp_2to3_detail_content in pulp_2to3_detail_qs.iterator(chunk_size=800):  <======= and then stuck here again for days
                dc = None
                pulp2content = pulp_2to3_detail_content.pulp2content
~~~

### PR DESCRIPTION
**Pull request by hao-yu**
Migration may stuck for many days when migrating an environment
with massive number of rpms.

closes #568

### CODE REVIEW

**Comment by hao-yu** [comment]
any chance we can review this?

**Comment by dralley** [comment]
@hao-yu Can you please rebase this?

**Comment by hao-yu** [comment]
done rebasing

**Comment by hao-yu** [comment]
for more information about this issue you can refer to https://bugzilla.redhat.com/show_bug.cgi?id=2097204

**Comment by dralley** [comment]
Could you fix the lint warnings also?

**Comment by hao-yu** [comment]
done

**Comment by dralley** [comment]
@hao-yu Could you paste the ORM-created query for comparison?  Do you have any comparisons of the output of the queries?

**Comment by hao-yu** [comment]
ORM created query:
~~~
pulpcore=# explain SELECT "pulp_2to3_migration_pulp2rpm"."pulp_id", "pulp_2to3_migration_pulp2rpm"."pulp_created", "pulp_2to3_migration_pulp2rpm"."pulp_last_updated", "pulp_2to3_migration_pulp2rpm"."pulp2content_id", "pulp_2to3_migration_pulp2rpm"."name", "pulp_2to3_migration_pulp2rpm"."epoch", "pulp_2to3_migration_pulp2rpm"."version", "pulp_2to3_migration_pulp2rpm"."release", "pulp_2to3_migration_pulp2rpm"."arch", "pulp_2to3_migration_pulp2rpm"."checksum", "pulp_2to3_migration_pulp2rpm"."checksumtype", "pulp_2to3_migration_pulp2rpm"."primary_template_gz", "pulp_2to3_migration_pulp2rpm"."filelists_template_gz", "pulp_2to3_migration_pulp2rpm"."other_template_gz", "pulp_2to3_migration_pulp2rpm"."is_modular", "pulp_2to3_migration_pulp2rpm"."size", "pulp_2to3_migration_pulp2rpm"."filename" FROM "pulp_2to3_migration_pulp2rpm" INNER JOIN "pulp_2to3_migration_pulp2content" ON ("pulp_2to3_migration_pulp2rpm"."pulp2content_id" = "pulp_2to3_migration_pulp2content"."pulp_id") WHERE NOT (NOT ("pulp_2to3_migration_pulp2content"."pulp3_content_id" IS NULL) AND NOT ("pulp_2to3_migration_pulp2content"."pulp2_id" IN (SELECT DISTINCT U0."pulp2_unit_id" FROM "pulp_2to3_migration_pulp2lazycatalog" U0 WHERE U0."is_migrated" = False)));
                                                                              QUERY PLAN                                                                              
----------------------------------------------------------------------------------------------------------------------------------------------------------------------
 Nested Loop  (cost=99882.46..1010580180.94 rows=134842 width=1459)
   ->  Gather Merge  (cost=99882.04..1010085228.53 rows=645078 width=16)
         Workers Planned: 2
         ->  Parallel Index Scan using pulp_2to3_migration_pulp2content_pkey on pulp_2to3_migration_pulp2content  (cost=98882.02..1010009770.50 rows=268782 width=16)
               Filter: ((pulp3_content_id IS NULL) OR (SubPlan 1))
               SubPlan 1
                 ->  Materialize  (cost=98881.59..102605.44 rows=119732 width=37)
                       ->  Unique  (cost=98881.59..101070.78 rows=119732 width=37)
                             ->  Sort  (cost=98881.59..99976.19 rows=437838 width=37)
                                   Sort Key: u0.pulp2_unit_id
                                   ->  Seq Scan on pulp_2to3_migration_pulp2lazycatalog u0  (cost=0.00..45882.59 rows=437838 width=37)
                                         Filter: (NOT is_migrated)
   ->  Index Scan using pulp_2to3_migration_pulp2rpm_pulp2content_id_508869c4 on pulp_2to3_migration_pulp2rpm  (cost=0.42..0.76 rows=1 width=1459)
         Index Cond: (pulp2content_id = pulp_2to3_migration_pulp2content.pulp_id)
~~~

Patch:
~~~
pulpcore=# explain SELECT "pulp_2to3_migration_pulp2rpm"."pulp_id", "pulp_2to3_migration_pulp2rpm"."pulp_created", "pulp_2to3_migration_pulp2rpm"."pulp_last_updated", "pulp_2to3_migration_pulp2rpm"."pulp2content_id", "pulp_2to3_migration_pulp2rpm"."name", "pulp_2to3_migration_pulp2rpm"."epoch", "pulp_2to3_migration_pulp2rpm"."version", "pulp_2to3_migration_pulp2rpm"."release", "pulp_2to3_migration_pulp2rpm"."arch", "pulp_2to3_migration_pulp2rpm"."checksum", "pulp_2to3_migration_pulp2rpm"."checksumtype", "pulp_2to3_migration_pulp2rpm"."primary_template_gz", "pulp_2to3_migration_pulp2rpm"."filelists_template_gz", "pulp_2to3_migration_pulp2rpm"."other_template_gz", "pulp_2to3_migration_pulp2rpm"."is_modular", "pulp_2to3_migration_pulp2rpm"."size", "pulp_2to3_migration_pulp2rpm"."filename" FROM "pulp_2to3_migration_pulp2rpm" WHERE "pulp_2to3_migration_pulp2rpm"."pulp_id" IN ((
pulpcore(#         SELECT DISTINCT pulp_2to3_migration_pulp2rpm.pulp_id
pulpcore(#           FROM pulp_2to3_migration_pulp2rpm
pulpcore(#           INNER JOIN pulp_2to3_migration_pulp2content ON
pulpcore(#             (pulp_2to3_migration_pulp2rpm.pulp2content_id =
pulpcore(#               pulp_2to3_migration_pulp2content.pulp_id
pulpcore(#             AND pulp_2to3_migration_pulp2content.pulp2_content_type_id = 'rpm')
pulpcore(#           LEFT JOIN pulp_2to3_migration_pulp2lazycatalog ON
pulpcore(#             (pulp_2to3_migration_pulp2content.pulp2_id =
pulpcore(#              pulp_2to3_migration_pulp2lazycatalog.pulp2_unit_id)
pulpcore(#           WHERE NOT (NOT (pulp_2to3_migration_pulp2content.pulp3_content_id IS NULL)
pulpcore(#             AND NOT (pulp_2to3_migration_pulp2lazycatalog.is_migrated = false))
pulpcore(#         ));
                                                                               QUERY PLAN                                                                               
------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 Hash Join  (cost=172845.17..317689.34 rows=197999 width=1459)
   Hash Cond: (pulp_2to3_migration_pulp2rpm.pulp_id = pulp_2to3_migration_pulp2rpm_1.pulp_id)
   ->  Seq Scan on pulp_2to3_migration_pulp2rpm  (cost=0.00..51736.14 rows=251814 width=1459)
   ->  Hash  (cost=169403.19..169403.19 rows=197999 width=16)
         ->  Unique  (cost=166433.20..167423.20 rows=197999 width=16)
               ->  Sort  (cost=166433.20..166928.20 rows=197999 width=16)
                     Sort Key: pulp_2to3_migration_pulp2rpm_1.pulp_id
                     ->  Gather  (cost=41110.47..145629.61 rows=197999 width=16)
                           Workers Planned: 2
                           ->  Nested Loop Left Join  (cost=40110.47..124829.71 rows=82500 width=16)
                                 Filter: ((pulp_2to3_migration_pulp2content.pulp3_content_id IS NULL) OR (NOT pulp_2to3_migration_pulp2lazycatalog.is_migrated))
                                 ->  Parallel Hash Join  (cost=40110.05..93310.69 rows=21785 width=69)
                                       Hash Cond: (pulp_2to3_migration_pulp2rpm_1.pulp2content_id = pulp_2to3_migration_pulp2content.pulp_id)
                                       ->  Parallel Seq Scan on pulp_2to3_migration_pulp2rpm pulp_2to3_migration_pulp2rpm_1  (cost=0.00..50267.22 rows=104922 width=32)
                                       ->  Parallel Hash  (cost=37585.30..37585.30 rows=104220 width=69)
                                             ->  Parallel Seq Scan on pulp_2to3_migration_pulp2content  (cost=0.00..37585.30 rows=104220 width=69)
                                                   Filter: ((pulp2_content_type_id)::text = 'rpm'::text)
                                 ->  Index Scan using pulp_2to3_m_pulp2_u_c60485_idx on pulp_2to3_migration_pulp2lazycatalog  (cost=0.42..1.39 rows=6 width=38)
                                       Index Cond: ((pulp2_unit_id)::text = (pulp_2to3_migration_pulp2content.pulp2_id)::text)
(19 rows)
~~~

**Review by dralley — APPROVED** [review]
Great work @hao-yu, and thanks for the comparison.

**Comment by dralley** [comment]
@ggainey For your benefit here's the SQL with more formatting

Bad:

```SQL
SELECT ${all the fields}
FROM "pulp_2to3_migration_pulp2rpm"
INNER JOIN "pulp_2to3_migration_pulp2content" ON (
    "pulp_2to3_migration_pulp2rpm"."pulp2content_id" = "pulp_2to3_migration_pulp2content"."pulp_id"
) WHERE NOT (
    NOT ("pulp_2to3_migration_pulp2content"."pulp3_content_id" IS NULL)
    AND NOT ("pulp_2to3_migration_pulp2content"."pulp2_id" IN (
        SELECT DISTINCT U0."pulp2_unit_id" FROM "pulp_2to3_migration_pulp2lazycatalog" U0 WHERE U0."is_migrated" = False)
    )
);
```

Good:

```SQL

SELECT ${all the fields}
FROM "pulp_2to3_migration_pulp2rpm"
WHERE "pulp_2to3_migration_pulp2rpm"."pulp_id" IN ((
    SELECT DISTINCT pulp_2to3_migration_pulp2rpm.pulp_id
    FROM pulp_2to3_migration_pulp2rpm
    INNER JOIN pulp_2to3_migration_pulp2content ON
        (pulp_2to3_migration_pulp2rpm.pulp2content_id = pulp_2to3_migration_pulp2content.pulp_id AND pulp_2to3_migration_pulp2content.pulp2_content_type_id = 'rpm')
    LEFT JOIN pulp_2to3_migration_pulp2lazycatalog ON
        (pulp_2to3_migration_pulp2content.pulp2_id = pulp_2to3_migration_pulp2lazycatalog.pulp2_unit_id)
    WHERE NOT (
        NOT (pulp_2to3_migration_pulp2content.pulp3_content_id IS NULL)
        AND NOT (pulp_2to3_migration_pulp2lazycatalog.is_migrated = false)
    )
));
```

**Review by ggainey — APPROVED** [review]
I like avoiding direct-sql in Django when/wherever we can - but sometimes you need to build the best query you can, rather than rely on the ORM to do the right thing.  Great work, thanks Hao!

**Comment by dralley** [comment]
@hao-yu It looks like this needs t obe manually cherrypicked

**Pull request merged**
