### PR TITLE
Add deb gpgkey migration

### PR DESCRIPTION
**Pull request by m-bucher**
Closes #8970
https://pulp.plan.io/issues/8970

### CODE REVIEW

**Comment by goosemania** [comment]
CI wants an entry in the changelog. For that, please create CHANGES/8970.bugfix with a user friendly description of what is fixed.

**Comment by m-bucher** [comment]
> CI wants an entry in the changelog. For that, please create CHANGES/8970.bugfix with a user friendly description of what is fixed.

:heavy_check_mark: @goosemania created it in the wrong folder :facepalm:

**Comment by goosemania** [comment]
Test failures are not related to your changes, we are investigating CI issues.

**Comment by goosemania** [comment]
@m-bucher , we fixed CI, please rebase

**Comment by m-bucher** [comment]
@goosemania done :grinning:

**Review by dralley — APPROVED** [review]

**Pull request merged**
